version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: cursonestjs-app
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: cursonestjs-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cursonestjs

  dbtest:
    build: .docker/postgres
    container_name: cursonestjs-dbtest
    restart: always
    tty: true
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbtest

  pgadmin:
    image: dpage/pgadmin4
    container_name: cursonestjs-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
